- name: Configure nginx web root folder in Ubuntu
  copy: src=default dest=/etc/nginx/sites-available/default
  when: ansible_distribution == "Ubuntu"

- name: Configure nginx web root folder in CentOS 
  when: ansible_distribution == "CentOS"
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf

- name: Create nginx web root folder
  file: path=/var/html state=directory mode=0777
  notify:
     - Restart nginx server
