- name: Demonstrates ansible vault feature
  hosts: all
  vars_files:
    - contacts.yml
  tasks:
    - name: Print contact details
      debug: msg="Mobile number of {{item.value.name}} is {{item.value.mobile}}."
      with_dict: "{{contacts}}"
